version: '3.8'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=local"

  host.api:
    image: host-api
    build:
      context: .
      dockerfile: src/Heimdall.Templates.DotNet.Microservice.Host.Api/Dockerfile
    ports:
      - "54323:54323"

  host.worker:
    image: host-worker
    build:
      context: .
      dockerfile: src/Heimdall.Templates.DotNet.Microservice.Host.Worker/Dockerfile